### ISSUE TITLE
running as non-root

### ISSUE THREAD

**Issue by swills** [hselasky/webcamd#15]
Just wondering, would it ever be possible to run webcamd as non-root? Perhaps if the cuse device were not owned by root? Would there be any real benefit?

**Comment by hselasky** [comment]
Yes, if both /dev/cuse and /dev/ugenX.Y is made available to webcamd.

The problem is that some operations requires re-opening of ugenX.Y, so you cannot just capsicum it :-(

If capsicum could support a regular expression for limiting access, syslogd, cuse, ugen, pidfile, that would be the best.

If you want to work on it, feel free to go ahead.

**Comment by swills** [comment]
Ok, I'll take a look. Closing this for now. If I make progress I'll re-open.
